# Min target
platform :ios, '13.0'

# Pod install settings
# Configured for using separate projects (more performant)
install! 'cocoapods',
generate_multiple_pod_projects: true,
incremental_installation: true
use_modular_headers!

# Open Source Cocoapods
source 'https://cdn.cocoapods.org'

def shared_pods
    pod 'OfflineRequestManager', :path => '../'
end

def test_pods
    pod 'Quick'
    pod 'Nimble'
end

target 'MSOfflineRequestManager-Example' do
    shared_pods
end

target 'MSOfflineRequestManager-ExampleTests' do
    shared_pods
    test_pods
end
