source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

def shared_pods
    pod 'MSOfflineRequestManager', :path => '../'
end

def test_pods
    pod 'Quick'
    pod 'Nimble'
end

target 'MSOfflineRequestManager-Example' do
    shared_pods
end

target 'MSOfflineRequestManager-ExampleTests' do
    shared_pods
  test_pods
end
